name: Keep Render Alive

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Render
        run: curl -I https://smart-bell.onrender.com/
